#!/bin/python

import subprocess
import sys

# first check that the controller is active. If not working. still try devices connected
status = subprocess.run(
    ["bluetoothctl", "show"],
    check=True,
    capture_output=True,
    text=True,
)

powerstate: None | str = None
if not status.returncode:
    lines: list[str] = status.stdout.split("\n")
    for line in lines:
        if line.strip().startswith("PowerState: "):
            powerstate = line.strip().removeprefix("PowerState: ")
            break

    if powerstate == "off":
        print("off")
        sys.exit(0)

# get info about connected device:
status = subprocess.run(
    ["bluetoothctl", "devices", "Connected"],
    check=True,
    capture_output=True,
    text=True,
)

# Device 88:88:88:88:88:88 device name

if status.returncode:
    print("none")
    sys.exit(1)

# find column sizes and names
lines: list[str] = status.stdout.split("\n")
connected_devices: list[str] = []
for line in lines:
    if line.startswith("Device "):
        device: str = line.removeprefix("Device ")
        # remove mac address (2 * 6) + (1 * 5) = 17
        device = device[18:]
        connected_devices.append(device)

if not connected_devices and powerstate is not None:
    print(powerstate)
else:
    print(" / ".join(connected_devices))

sys.exit(0)
